import type { Metadata } from "next";
import { Paytone_One, Nunito } from "next/font/google";
import "./globals.css";

const paytoneOne = Paytone_One({
  variable: "--font-paytone-one",
  subsets: ["latin"],
  weight: "400",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${paytoneOne.variable} ${nunito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
